// Chat realtime: Firestore menyimpan pesan, Socket.io menangani typing/presence.
let me=null,socket=null,room='general',selectedFile=null,typingTimer=null;
const messages=document.getElementById('messages'),input=document.getElementById('messageInput'),typing=document.getElementById('typing');
const rendered=new Set();
function addMessage(m,id){id=id||m.id;if(rendered.has(id))return;rendered.add(id);const mine=m.senderId===me?.uid;const row=document.createElement('div');row.className=`message ${mine?'me':'them'} animate__animated animate__fadeInUp`;row.dataset.id=id;let body='';if(m.fileURL){if((m.fileType||'').startsWith('image/'))body=`<a href="${m.fileURL}" target="_blank"><img src="${m.fileURL}" alt="Lampiran" style="max-width:100%;max-height:280px;border-radius:12px" loading="lazy"></a>`;else if((m.fileType||'').startsWith('audio/'))body=`<audio controls src="${m.fileURL}" style="max-width:100%"></audio>`;else if((m.fileType||'').startsWith('video/'))body=`<video controls src="${m.fileURL}" style="max-width:100%;max-height:300px;border-radius:12px"></video>`;else body=`<a href="${m.fileURL}" target="_blank" rel="noopener">📎 ${App.sanitize(m.fileName||'Unduh dokumen')}</a>`}if(m.text)body+=`<div>${App.sanitize(m.text)}</div>`;const t=m.createdAt?.toDate?m.createdAt.toDate():new Date(m.createdAt||Date.now());row.innerHTML=`<div class="bubble">${body||'Pesan'}<div class="msg-time">${t.toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'})} ${mine?'✓✓':''}</div></div>`;messages.append(row);messages.scrollTop=messages.scrollHeight}
function clearDemo(){messages.querySelectorAll('.message').forEach(x=>x.remove())}
async function initChat(user){me=user;document.querySelectorAll('.side-head b').forEach(e=>e.textContent=user.name||user.displayName||'Pengguna');
 if(typeof io!=='undefined'){socket=io();socket.emit('user:join',{uid:user.uid,displayName:user.name||user.displayName});socket.emit('room:join',room);socket.on('typing',d=>typing.textContent=d.isTyping?'Teman sedang mengetik…':'');}
 const fb=window.AiratuFirebase;if(fb?.db){clearDemo();fb.db.collection('rooms').doc(room).collection('messages').orderBy('createdAt','asc').limitToLast(100).onSnapshot(s=>s.docChanges().forEach(c=>{if(c.type==='added')addMessage(c.doc.data(),c.doc.id)}),e=>{console.error(e);App.toast('Firestore belum siap. Periksa Rules pada README.','danger')});}
}
window.addEventListener('airatu-auth-ready',e=>initChat(e.detail));
if(window.airatuCurrentUser)initChat(window.airatuCurrentUser);
document.getElementById('sendForm')?.addEventListener('submit',async e=>{e.preventDefault();const text=input.value.trim();if(!text&&!selectedFile)return;const btn=e.submitter;btn.disabled=true;try{let fileURL='',fileType='',fileName='';if(selectedFile){if(selectedFile.size>20*1024*1024)throw new Error('Ukuran file maksimal 20 MB');if(!AiratuFirebase.storage)throw new Error('Firebase Storage belum aktif');fileType=selectedFile.type;fileName=selectedFile.name;const ref=AiratuFirebase.storage.ref(`chat/${room}/${me.uid}/${Date.now()}-${fileName.replace(/[^a-zA-Z0-9._-]/g,'_')}`);await ref.put(selectedFile,{contentType:fileType});fileURL=await ref.getDownloadURL()}
 const data={senderId:me.uid,senderName:me.name||me.displayName||'',text,fileURL,fileType,fileName,status:'sent',createdAt:firebase.firestore.FieldValue.serverTimestamp()};if(AiratuFirebase.db)await AiratuFirebase.db.collection('rooms').doc(room).collection('messages').add(data);else addMessage({...data,createdAt:Date.now()},crypto.randomUUID());input.value='';selectedFile=null;document.getElementById('fileInput').value='';socket?.emit('typing',{roomId:room,isTyping:false});}catch(err){App.toast(err.message,'danger')}finally{btn.disabled=false}});
input?.addEventListener('input',()=>{socket?.emit('typing',{roomId:room,isTyping:true});clearTimeout(typingTimer);typingTimer=setTimeout(()=>socket?.emit('typing',{roomId:room,isTyping:false}),900)});
document.querySelectorAll('.chat-item').forEach(x=>x.onclick=()=>document.querySelector('.chat-app').classList.add('open'));document.getElementById('back')?.addEventListener('click',()=>document.querySelector('.chat-app').classList.remove('open'));document.getElementById('fileInput')?.addEventListener('change',e=>{selectedFile=e.target.files[0]||null;if(selectedFile)App.toast(`${selectedFile.name} siap dikirim`)});
