const fb=window.AiratuFirebase;
function friendly(err){const m={'auth/email-already-in-use':'Email sudah terdaftar. Silakan masuk.','auth/weak-password':'Password minimal 6 karakter.','auth/invalid-email':'Format email tidak valid.','auth/popup-closed-by-user':'Jendela Google ditutup.','auth/unauthorized-domain':'Domain belum diizinkan pada Firebase Authentication.','auth/network-request-failed':'Koneksi Firebase gagal.'};return m[err.code]||err.message}
async function createProfile(user,data={}){
 let photoURL=user.photoURL||'';
 const file=document.querySelector('[name="photo"]')?.files[0];
 if(file&&fb.storage){if(file.size>5*1024*1024)throw new Error('Foto maksimal 5 MB');const ref=fb.storage.ref(`profiles/${user.uid}/profile-${Date.now()}`);await ref.put(file,{contentType:file.type});photoURL=await ref.getDownloadURL();await user.updateProfile({photoURL})}
 const profile={uid:user.uid,name:data.name||user.displayName||'Pengguna AiratuKL',username:data.username||`user_${user.uid.slice(0,7)}`,email:user.email||data.email||'',phone:user.phoneNumber||data.phone||'',birthdate:data.birthdate||'',gender:data.gender||'',status:data.status||'Hai, saya baru di AiratuKL!',bio:'',photoURL,level:0,totalExp:0,wins:0,matches:0,role:'user',createdAt:firebase.firestore.FieldValue.serverTimestamp()};
 if(fb.db){try{await fb.db.collection('users').doc(user.uid).set(profile,{merge:true})}catch(error){console.warn('Profil belum tersimpan ke Firestore. Terapkan firestore.rules:',error)}}localStorage.setItem('airatu_user',JSON.stringify({...profile,createdAt:null}));location.replace('chat.html');
}
document.getElementById('registerForm')?.addEventListener('submit',async e=>{e.preventDefault();const btn=e.submitter,f=new FormData(e.target);if(f.get('password')!==f.get('confirm'))return App.toast('Konfirmasi password tidak sama','danger');btn.disabled=true;btn.textContent='Membuat akun…';try{const data=Object.fromEntries(f);const result=await fb.auth.createUserWithEmailAndPassword(data.email.trim(),data.password);await result.user.updateProfile({displayName:data.name});await createProfile(result.user,data)}catch(err){App.toast(friendly(err),'danger');btn.disabled=false;btn.textContent='Daftar sekarang'}});
document.getElementById('googleRegister')?.addEventListener('click',async e=>{const btn=e.currentTarget;btn.disabled=true;try{const provider=new firebase.auth.GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});const result=await fb.auth.signInWithPopup(provider);await createProfile(result.user)}catch(err){App.toast(friendly(err),'danger');btn.disabled=false}});
