const path = require('path');
const express = require('express');
const helmet = require('helmet');
const cors = require('cors');
const compression = require('compression');
const rateLimit = require('express-rate-limit');
const http = require('http');
const initSocket = require('./socket');
const app = express();
const server = http.createServer(app);
app.use(helmet({ contentSecurityPolicy: false }));
app.use(cors({ origin: true, credentials: true }));
app.use(compression());
app.use(express.json({limit:'1mb'}));
app.use('/api', rateLimit({windowMs:60_000,max:120,standardHeaders:true}));
app.use(express.static(path.join(__dirname,'..'), {maxAge:'1h',extensions:['html']}));
app.get('/api/health',(_,res)=>res.json({ok:true,service:'AiratuKL',time:new Date().toISOString()}));
app.get('*',(_,res)=>res.sendFile(path.join(__dirname,'..','index.html')));
initSocket(server);
const PORT=process.env.PORT||3000;
server.listen(PORT,()=>console.log(`AiratuKL aktif: http://localhost:${PORT}`));
